{
    'name': 'دورة الإيجار السعودية الكاملة',
    'version': '17.0.1.0.0',
    'category': 'Real Estate',
    'summary': 'دورة إيجار كاملة: جدول دفع، تحصيل، تنبيهات، صيانة، إنهاء',
    'author': 'Abdelrehman Elhaj',
    'license': 'LGPL-3',
    'depends': [
        'sa_property',
        'l10n_sa_ejar',
        'sa_maintenance',
        'account',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sa_rental_cron.xml',
        'views/sa_rent_payment_views.xml',
        'views/sa_tenancy_cycle_views.xml',
        'views/owner_dashboard_views.xml',
        'views/compliance_reports.xml',
        'wizard/sa_end_tenancy_wizard_views.xml',
        'wizard/sa_payment_wizard_views.xml',
        'wizard/sa_tenancy_renewal_wizard_views.xml',
        'views/menu.xml',
        'report/tenant_statement_report.xml',
    ],
    'installable': True,
    'auto_install': False,
}
