from . import telephony_gateway
from . import telephony_asterisk_service
from . import telephony_twilio_service
from . import call_center_queue
from . import call_center_call
from . import call_center_ticket
from . import res_users
from . import res_partner
from . import res_config_settings
