{
    'name': 'إدارة العملاء العقاريين',
    'name_en': 'Saudi Real Estate CRM',
    'version': '17.0.1.0.0',
    'category': 'Real Estate',
    'summary': 'إدارة العملاء المحتملين وفرص البيع والإيجار للوساطة العقارية',
    'author': 'Abdelrehman Elhaj',
    'website': 'https://proptech.sa',
    'license': 'LGPL-3',
    'depends': ['sa_property_base', 'sa_security', 'l10n_sa_ejar'],
    'data': [
        'security/ir.model.access.csv',
        'security/sa_crm_security.xml',
        'data/sequence.xml',
        'data/sa_crm_stage_data.xml',
        'views/sa_crm_stage_views.xml',
        'views/sa_crm_showing_views.xml',
        'views/sa_crm_reservation_views.xml',
        'views/sa_crm_lead_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
